export enum Rules{
   RULE_BOMB_HURT = 0,
   RULE_BOMB_INFINITE = 1,
   RULE_BOMB_NORMAL =2,
   RULE_KEY_HURT = 3,
   RULE_KEY_INFINITE = 4,
   RULE_KEY_NORMAL =5,
   RULE_COIN_HURT = 6,
   RULE_COIN_INFINITE = 7,
   RULE_COIN_NORMAL =8,
  }